# Generated by Django 5.1.3 on 2024-11-26 16:47

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartoCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siret', models.TextField(db_index=True)),
                ('nom_etablissement', models.TextField(blank=True, null=True)),
                ('profils', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('profils_collecteur', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('profils_installation', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('bsdd', models.BooleanField(blank=True, null=True)),
                ('bsdnd', models.BooleanField(blank=True, null=True)),
                ('bsda', models.BooleanField(blank=True, null=True)),
                ('bsff', models.BooleanField(blank=True, null=True)),
                ('bsdasri', models.BooleanField(blank=True, null=True)),
                ('bsvhu', models.BooleanField(blank=True, null=True)),
                ('texs_dd', models.BooleanField(blank=True, null=True)),
                ('dnd', models.BooleanField(blank=True, null=True)),
                ('texs', models.BooleanField(blank=True, null=True)),
                ('ssd', models.BooleanField(blank=True, null=True)),
                ('pnttd', models.BooleanField(blank=True, null=True)),
                ('processing_operations_bsdd', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('processing_operations_bsdnd', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('processing_operations_bsda', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('processing_operations_bsff', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('processing_operations_bsdasri', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('processing_operations_bsvhu', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('processing_operation_dnd', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('processing_operation_texs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('code_commune_insee', models.CharField(blank=True, max_length=255, null=True)),
                ('code_departement_insee', models.CharField(blank=True, null=True)),
                ('code_region_insee', models.IntegerField(blank=True, null=True)),
                ('adresse_td', models.TextField(blank=True, null=True)),
                ('adresse_insee', models.TextField(blank=True, null=True)),
                ('latitude_td', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('longitude_td', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('latitude_ban', models.FloatField(blank=True, null=True)),
                ('longitude_ban', models.FloatField(blank=True, null=True)),
                ('coords', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Établissement',
                'verbose_name_plural': 'Établissements',
            },
        ),
    ]
