# Generated by Django 5.1.6 on 2025-04-07 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartoCompany',
        ),
    ]
