# Generated by Django 5.1.6 on 2025-02-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartocompany',
            name='bsda_destination',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartocompany',
            name='bsda_emitter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartocompany',
            name='bsda_transporter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartocompany',
            name='bsdasri_destination',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartocompany',
            name='bsdasri_emitter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartocompany',
            name='bsdasri_transporter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartocompany',
            name='bsdd_destination',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartocompany',
            name='bsdd_emitter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartocompany',
            name='bsdd_transporter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartocompany',
            name='bsdnd_destination',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartocompany',
            name='bsdnd_emitter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartocompany',
            name='bsdnd_transporter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartocompany',
            name='bsff_destination',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartocompany',
            name='bsff_emitter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartocompany',
            name='bsff_transporter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartocompany',
            name='bsvhu_destination',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartocompany',
            name='bsvhu_emitter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartocompany',
            name='bsvhu_transporter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartocompany',
            name='dnd_destination',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartocompany',
            name='dnd_emitter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartocompany',
            name='texs_dd_destination',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartocompany',
            name='texs_dd_emitter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartocompany',
            name='texs_dd_transporter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartocompany',
            name='texs_destination',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartocompany',
            name='texs_emitter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartocompany',
            name='waste_codes_bordereaux',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartocompany',
            name='waste_codes_dnd_statements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartocompany',
            name='waste_codes_processed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartocompany',
            name='waste_codes_texs_statements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
