# Generated by Django 5.1.6 on 2025-03-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_cartocompany_bsda_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartocompany',
            name='latitude_ban',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='cartocompany',
            name='longitude_ban',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
