# Generated by Django 5.2 on 2025-04-10 08:18

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maps', '0002_remove_carto_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartoCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siret', models.TextField(db_index=True)),
                ('nom_etablissement', models.TextField(blank=True, null=True)),
                ('profils', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('profils_collecteur', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('profils_installation', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('profils_installation_vhu', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('bsdd', models.BooleanField(blank=True, null=True)),
                ('bsdd_emitter', models.BooleanField(default=False)),
                ('bsdd_transporter', models.BooleanField(default=False)),
                ('bsdd_destination', models.BooleanField(default=False)),
                ('bsdnd', models.BooleanField(blank=True, null=True)),
                ('bsdnd_emitter', models.BooleanField(default=False)),
                ('bsdnd_transporter', models.BooleanField(default=False)),
                ('bsdnd_destination', models.BooleanField(default=False)),
                ('bsda', models.BooleanField(blank=True, db_index=True, null=True)),
                ('bsda_emitter', models.BooleanField(default=False)),
                ('bsda_transporter', models.BooleanField(default=False)),
                ('bsda_destination', models.BooleanField(default=False)),
                ('bsda_worker', models.BooleanField(default=False)),
                ('bsff', models.BooleanField(blank=True, null=True)),
                ('bsff_emitter', models.BooleanField(default=False)),
                ('bsff_transporter', models.BooleanField(default=False)),
                ('bsff_destination', models.BooleanField(default=False)),
                ('bsdasri', models.BooleanField(blank=True, null=True)),
                ('bsdasri_emitter', models.BooleanField(default=False)),
                ('bsdasri_transporter', models.BooleanField(default=False)),
                ('bsdasri_destination', models.BooleanField(default=False)),
                ('bsvhu', models.BooleanField(blank=True, db_index=True, null=True)),
                ('bsvhu_emitter', models.BooleanField(db_index=True, default=False)),
                ('bsvhu_transporter', models.BooleanField(db_index=True, default=False)),
                ('bsvhu_destination', models.BooleanField(db_index=True, default=False)),
                ('texs_dd', models.BooleanField(blank=True, db_index=True, null=True)),
                ('texs_dd_emitter', models.BooleanField(db_index=True, default=False)),
                ('texs_dd_transporter', models.BooleanField(db_index=True, default=False)),
                ('texs_dd_destination', models.BooleanField(db_index=True, default=False)),
                ('dnd', models.BooleanField(blank=True, db_index=True, null=True)),
                ('dnd_emitter', models.BooleanField(db_index=True, default=False)),
                ('dnd_destination', models.BooleanField(db_index=True, default=False)),
                ('texs', models.BooleanField(blank=True, db_index=True, null=True)),
                ('texs_emitter', models.BooleanField(db_index=True, default=False)),
                ('texs_destination', models.BooleanField(db_index=True, default=False)),
                ('ssd', models.BooleanField(blank=True, null=True)),
                ('pnttd', models.BooleanField(blank=True, null=True)),
                ('processing_operations_bsdd', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('processing_operations_bsdnd', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('processing_operations_bsda', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('processing_operations_bsff', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('processing_operations_bsdasri', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('processing_operations_bsvhu', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('processing_operation_dnd', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('processing_operation_texs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('waste_codes_bordereaux', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('waste_codes_dnd_statements', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('waste_codes_texs_statements', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('waste_codes_processed', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('code_commune_insee', models.CharField(blank=True, max_length=255, null=True)),
                ('code_departement_insee', models.CharField(blank=True, db_index=True, null=True)),
                ('code_region_insee', models.IntegerField(blank=True, db_index=True, null=True)),
                ('adresse_td', models.TextField(blank=True, null=True)),
                ('adresse_insee', models.TextField(blank=True, null=True)),
                ('coords', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Établissement',
                'verbose_name_plural': 'Établissements',
                'indexes': [models.Index(fields=['bsdd', 'bsdd_emitter'], name='maps_cartoc_bsdd_9bf806_idx'), models.Index(fields=['bsdd', 'bsdd_transporter'], name='maps_cartoc_bsdd_89384a_idx'), models.Index(fields=['bsdd', 'bsdd_destination'], name='maps_cartoc_bsdd_e312e3_idx'), models.Index(fields=['bsda', 'bsda_emitter'], name='maps_cartoc_bsda_ab0725_idx'), models.Index(fields=['bsda', 'bsda_transporter'], name='maps_cartoc_bsda_8609ff_idx'), models.Index(fields=['bsda', 'bsda_destination'], name='maps_cartoc_bsda_66f7de_idx'), models.Index(fields=['bsda', 'bsda_worker'], name='maps_cartoc_bsda_cc84f0_idx'), models.Index(fields=['bsff', 'bsff_emitter'], name='maps_cartoc_bsff_5ff2b4_idx'), models.Index(fields=['bsff', 'bsff_transporter'], name='maps_cartoc_bsff_8c3425_idx'), models.Index(fields=['bsff', 'bsff_destination'], name='maps_cartoc_bsff_997bde_idx'), models.Index(fields=['bsdasri', 'bsdasri_emitter'], name='maps_cartoc_bsdasri_547344_idx'), models.Index(fields=['bsdasri', 'bsdasri_transporter'], name='maps_cartoc_bsdasri_6c78e8_idx'), models.Index(fields=['bsdasri', 'bsdasri_destination'], name='maps_cartoc_bsdasri_7deeee_idx'), models.Index(fields=['bsvhu', 'bsvhu_emitter'], name='maps_cartoc_bsvhu_060662_idx'), models.Index(fields=['bsvhu', 'bsvhu_transporter'], name='maps_cartoc_bsvhu_559c9b_idx'), models.Index(fields=['bsvhu', 'bsvhu_destination'], name='maps_cartoc_bsvhu_a0a2a4_idx'), models.Index(fields=['bsdnd', 'bsdnd_emitter'], name='maps_cartoc_bsdnd_3ca343_idx'), models.Index(fields=['bsdnd', 'bsdnd_transporter'], name='maps_cartoc_bsdnd_379e8f_idx'), models.Index(fields=['bsdnd', 'bsdnd_destination'], name='maps_cartoc_bsdnd_1c2c57_idx'), models.Index(fields=['texs_dd', 'texs_dd_emitter'], name='maps_cartoc_texs_dd_14878e_idx'), models.Index(fields=['texs_dd', 'texs_dd_transporter'], name='maps_cartoc_texs_dd_c4907e_idx'), models.Index(fields=['texs_dd', 'texs_dd_destination'], name='maps_cartoc_texs_dd_e06838_idx'), models.Index(fields=['dnd', 'dnd_emitter'], name='maps_cartoc_dnd_706369_idx'), models.Index(fields=['dnd', 'dnd_destination'], name='maps_cartoc_dnd_050141_idx'), models.Index(fields=['texs', 'texs_emitter'], name='maps_cartoc_texs_e209bc_idx'), models.Index(fields=['texs', 'texs_destination'], name='maps_cartoc_texs_a197ec_idx'), models.Index(fields=['siret'], name='maps_cartoc_siret_d88b54_idx'), models.Index(fields=['code_departement_insee'], name='maps_cartoc_code_de_39c6e5_idx'), models.Index(fields=['code_region_insee'], name='maps_cartoc_code_re_88df55_idx'), django.contrib.postgres.indexes.GinIndex(fields=['profils'], name='maps_cartoc_profils_c4930b_gin'), django.contrib.postgres.indexes.GinIndex(fields=['profils_collecteur'], name='maps_cartoc_profils_3d7cd2_gin'), django.contrib.postgres.indexes.GinIndex(fields=['profils_installation'], name='maps_cartoc_profils_104b75_gin'), django.contrib.postgres.indexes.GinIndex(fields=['profils_installation_vhu'], name='maps_cartoc_profils_9ec7fc_gin'), django.contrib.postgres.indexes.GinIndex(fields=['processing_operations_bsdd'], name='maps_cartoc_process_673801_gin'), django.contrib.postgres.indexes.GinIndex(fields=['processing_operations_bsdnd'], name='maps_cartoc_process_4daffd_gin'), django.contrib.postgres.indexes.GinIndex(fields=['processing_operations_bsda'], name='maps_cartoc_process_1cc82c_gin'), django.contrib.postgres.indexes.GinIndex(fields=['processing_operations_bsff'], name='maps_cartoc_process_293b53_gin'), django.contrib.postgres.indexes.GinIndex(fields=['processing_operations_bsdasri'], name='maps_cartoc_process_fbd06f_gin'), django.contrib.postgres.indexes.GinIndex(fields=['processing_operations_bsvhu'], name='maps_cartoc_process_b0aff5_gin'), django.contrib.postgres.indexes.GinIndex(fields=['processing_operation_dnd'], name='maps_cartoc_process_d1e834_gin'), django.contrib.postgres.indexes.GinIndex(fields=['processing_operation_texs'], name='maps_cartoc_process_6d0266_gin'), django.contrib.postgres.indexes.GinIndex(fields=['waste_codes_bordereaux'], name='maps_cartoc_waste_c_82f1d1_gin')],
            },
        ),
    ]
