# Generated by Django 5.1.7 on 2025-04-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartocompany',
            name='date_inscription',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='cartocompany',
            constraint=models.UniqueConstraint(fields=('siret',), name='unique_siret'),
        ),
    ]
