# Generated by Django 5.1.6 on 2025-03-31 12:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_alter_cartocompany_latitude_ban_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartocompany',
            name='latitude_ban',
        ),
        migrations.RemoveField(
            model_name='cartocompany',
            name='latitude_td',
        ),
        migrations.RemoveField(
            model_name='cartocompany',
            name='longitude_ban',
        ),
        migrations.RemoveField(
            model_name='cartocompany',
            name='longitude_td',
        ),
        migrations.AlterField(
            model_name='cartocompany',
            name='waste_codes_bordereaux',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='cartocompany',
            name='waste_codes_dnd_statements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='cartocompany',
            name='waste_codes_processed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='cartocompany',
            name='waste_codes_texs_statements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
