# Generated by Django 5.1.6 on 2025-04-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_remove_cartocompany_latitude_ban_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartocompany',
            name='bsda',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartocompany',
            name='bsdasri',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartocompany',
            name='bsdd',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartocompany',
            name='bsdnd',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartocompany',
            name='bsff',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartocompany',
            name='bsvhu',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='cartocompany',
            index=models.Index(fields=['bsdd', 'bsdd_emitter'], name='maps_cartoc_bsdd_9bf806_idx'),
        ),
        migrations.AddIndex(
            model_name='cartocompany',
            index=models.Index(fields=['bsdd', 'bsdd_transporter'], name='maps_cartoc_bsdd_89384a_idx'),
        ),
        migrations.AddIndex(
            model_name='cartocompany',
            index=models.Index(fields=['bsdd', 'bsdd_destination'], name='maps_cartoc_bsdd_e312e3_idx'),
        ),
        migrations.AddIndex(
            model_name='cartocompany',
            index=models.Index(fields=['bsda', 'bsda_emitter'], name='maps_cartoc_bsda_ab0725_idx'),
        ),
        migrations.AddIndex(
            model_name='cartocompany',
            index=models.Index(fields=['bsda', 'bsda_transporter'], name='maps_cartoc_bsda_8609ff_idx'),
        ),
        migrations.AddIndex(
            model_name='cartocompany',
            index=models.Index(fields=['bsda', 'bsda_destination'], name='maps_cartoc_bsda_66f7de_idx'),
        ),
        migrations.AddIndex(
            model_name='cartocompany',
            index=models.Index(fields=['bsff', 'bsff_emitter'], name='maps_cartoc_bsff_5ff2b4_idx'),
        ),
        migrations.AddIndex(
            model_name='cartocompany',
            index=models.Index(fields=['bsff', 'bsff_transporter'], name='maps_cartoc_bsff_8c3425_idx'),
        ),
        migrations.AddIndex(
            model_name='cartocompany',
            index=models.Index(fields=['bsff', 'bsff_destination'], name='maps_cartoc_bsff_997bde_idx'),
        ),
        migrations.AddIndex(
            model_name='cartocompany',
            index=models.Index(fields=['bsdasri', 'bsdasri_emitter'], name='maps_cartoc_bsdasri_547344_idx'),
        ),
        migrations.AddIndex(
            model_name='cartocompany',
            index=models.Index(fields=['bsdasri', 'bsdasri_transporter'], name='maps_cartoc_bsdasri_6c78e8_idx'),
        ),
        migrations.AddIndex(
            model_name='cartocompany',
            index=models.Index(fields=['bsdasri', 'bsdasri_destination'], name='maps_cartoc_bsdasri_7deeee_idx'),
        ),
        migrations.AddIndex(
            model_name='cartocompany',
            index=models.Index(fields=['bsvhu', 'bsvhu_emitter'], name='maps_cartoc_bsvhu_060662_idx'),
        ),
        migrations.AddIndex(
            model_name='cartocompany',
            index=models.Index(fields=['bsvhu', 'bsvhu_transporter'], name='maps_cartoc_bsvhu_559c9b_idx'),
        ),
        migrations.AddIndex(
            model_name='cartocompany',
            index=models.Index(fields=['bsvhu', 'bsvhu_destination'], name='maps_cartoc_bsvhu_a0a2a4_idx'),
        ),
        migrations.AddIndex(
            model_name='cartocompany',
            index=models.Index(fields=['bsdnd', 'bsdnd_emitter'], name='maps_cartoc_bsdnd_3ca343_idx'),
        ),
        migrations.AddIndex(
            model_name='cartocompany',
            index=models.Index(fields=['bsdnd', 'bsdnd_transporter'], name='maps_cartoc_bsdnd_379e8f_idx'),
        ),
        migrations.AddIndex(
            model_name='cartocompany',
            index=models.Index(fields=['bsdnd', 'bsdnd_destination'], name='maps_cartoc_bsdnd_1c2c57_idx'),
        ),
        migrations.AddIndex(
            model_name='cartocompany',
            index=models.Index(fields=['texs_dd', 'texs_dd_emitter'], name='maps_cartoc_texs_dd_14878e_idx'),
        ),
        migrations.AddIndex(
            model_name='cartocompany',
            index=models.Index(fields=['texs_dd', 'texs_dd_transporter'], name='maps_cartoc_texs_dd_c4907e_idx'),
        ),
        migrations.AddIndex(
            model_name='cartocompany',
            index=models.Index(fields=['texs_dd', 'texs_dd_destination'], name='maps_cartoc_texs_dd_e06838_idx'),
        ),
        migrations.AddIndex(
            model_name='cartocompany',
            index=models.Index(fields=['dnd', 'dnd_emitter'], name='maps_cartoc_dnd_706369_idx'),
        ),
        migrations.AddIndex(
            model_name='cartocompany',
            index=models.Index(fields=['dnd', 'dnd_destination'], name='maps_cartoc_dnd_050141_idx'),
        ),
        migrations.AddIndex(
            model_name='cartocompany',
            index=models.Index(fields=['texs', 'texs_emitter'], name='maps_cartoc_texs_e209bc_idx'),
        ),
        migrations.AddIndex(
            model_name='cartocompany',
            index=models.Index(fields=['texs', 'texs_destination'], name='maps_cartoc_texs_a197ec_idx'),
        ),
        migrations.AddIndex(
            model_name='cartocompany',
            index=models.Index(fields=['siret'], name='maps_cartoc_siret_d88b54_idx'),
        ),
        migrations.AddIndex(
            model_name='cartocompany',
            index=models.Index(fields=['code_departement_insee'], name='maps_cartoc_code_de_39c6e5_idx'),
        ),
        migrations.AddIndex(
            model_name='cartocompany',
            index=models.Index(fields=['code_region_insee'], name='maps_cartoc_code_re_88df55_idx'),
        ),
    ]
