# Generated by Django 5.2 on 2025-05-08 08:04

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_cartocompany_date_inscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartementsComputation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField(default=2023)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('rubrique', models.TextField()),
                ('quantite_autorisee', models.FloatField(null=True)),
                ('taux_consommation', models.FloatField(null=True)),
                ('cumul_quantite_traitee', models.FloatField(null=True)),
                ('moyenne_quantite_journaliere_traitee', models.FloatField(null=True)),
                ('graph', models.JSONField(default=dict, null=True)),
                ('code_departement_insee', models.TextField()),
                ('nom_departement', models.TextField()),
                ('code_region_insee', models.TextField()),
                ('nombre_installations', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Department Computation',
                'verbose_name_plural': 'Department Computations',
                'ordering': ('-created',),
                'indexes': [models.Index(fields=['year', 'rubrique'], name='maps_depart_year_a82775_idx'), models.Index(fields=['year', 'rubrique', 'code_departement_insee'], name='maps_depart_year_a1935f_idx')],
            },
        ),
        migrations.CreateModel(
            name='FranceComputation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField(default=2023)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('rubrique', models.TextField()),
                ('quantite_autorisee', models.FloatField(null=True)),
                ('taux_consommation', models.FloatField(null=True)),
                ('cumul_quantite_traitee', models.FloatField(null=True)),
                ('moyenne_quantite_journaliere_traitee', models.FloatField(null=True)),
                ('graph', models.JSONField(default=dict, null=True)),
                ('nombre_installations', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'France Computation',
                'verbose_name_plural': 'France Computations',
                'ordering': ('-created',),
                'indexes': [models.Index(fields=['year', 'rubrique'], name='maps_france_year_1cc107_idx')],
            },
        ),
        migrations.CreateModel(
            name='InstallationsComputation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField(default=2023)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('rubrique', models.TextField()),
                ('quantite_autorisee', models.FloatField(null=True)),
                ('taux_consommation', models.FloatField(null=True)),
                ('cumul_quantite_traitee', models.FloatField(null=True)),
                ('moyenne_quantite_journaliere_traitee', models.FloatField(null=True)),
                ('graph', models.JSONField(default=dict, null=True)),
                ('code_aiot', models.TextField()),
                ('raison_sociale', models.TextField(null=True)),
                ('siret', models.TextField(null=True)),
                ('adresse1', models.TextField(null=True)),
                ('adresse2', models.TextField(null=True)),
                ('code_postal', models.TextField(null=True)),
                ('commune', models.TextField(null=True)),
                ('etat_activite', models.TextField(null=True)),
                ('regime', models.TextField(null=True)),
                ('unite', models.TextField(null=True)),
                ('latitude', models.FloatField(default=None, null=True)),
                ('longitude', models.FloatField(default=None, null=True)),
            ],
            options={
                'verbose_name': 'Installations Computation',
                'verbose_name_plural': 'Installations Computations',
                'ordering': ('-created',),
                'indexes': [models.Index(fields=['year', 'rubrique'], name='maps_instal_year_0b1385_idx'), models.Index(fields=['year', 'rubrique', 'code_aiot'], name='maps_instal_year_92591d_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegionsComputation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField(default=2023)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('rubrique', models.TextField()),
                ('quantite_autorisee', models.FloatField(null=True)),
                ('taux_consommation', models.FloatField(null=True)),
                ('cumul_quantite_traitee', models.FloatField(null=True)),
                ('moyenne_quantite_journaliere_traitee', models.FloatField(null=True)),
                ('graph', models.JSONField(default=dict, null=True)),
                ('code_region_insee', models.TextField()),
                ('nom_region', models.TextField()),
                ('nombre_installations', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Regions Computation',
                'verbose_name_plural': 'Regions Computations',
                'ordering': ('-created',),
                'indexes': [models.Index(fields=['year', 'rubrique'], name='maps_region_year_c7cc65_idx'), models.Index(fields=['year', 'rubrique', 'code_region_insee'], name='maps_region_year_62325a_idx')],
            },
        ),
    ]
