# Generated by Django 5.1.6 on 2025-04-01 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_alter_cartocompany_bsda_alter_cartocompany_bsdasri_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE INDEX waste_codes_any_idx ON maps_cartocompany 
            (siret) WHERE (
                waste_codes_bordereaux IS NOT NULL 
                OR waste_codes_dnd_statements IS NOT NULL 
                OR waste_codes_processed IS NOT NULL
            );
            """,
            reverse_sql="DROP INDEX IF EXISTS waste_codes_any_idx;"
        ),
    ]
