# Generated by Django 4.1.7 on 2023-05-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeedbackResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Contenu")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date"),
                ),
                (
                    "author",
                    models.EmailField(max_length=254, verbose_name="Rempli par"),
                ),
            ],
            options={
                "verbose_name": "Résultat",
                "verbose_name_plural": "Résultats",
                "ordering": ("-created",),
            },
        ),
    ]
