# Generated by Django 5.1 on 2024-08-27 14:55

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import roadcontrol.models
import roadcontrol.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfBundle',
            fields=[
                ('company_siret', models.CharField(blank=True, max_length=20, verbose_name='Company Siret')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Company Name')),
                ('company_address', models.CharField(blank=True, max_length=512, verbose_name='Company Address')),
                ('company_contact', models.CharField(blank=True, max_length=255, verbose_name='Company Contact')),
                ('company_email', models.EmailField(blank=True, max_length=255, verbose_name='Company Email')),
                ('company_phone', models.CharField(blank=True, max_length=20, verbose_name='Company Phone')),
                ('transporter_plate', models.CharField(blank=True, max_length=20, verbose_name='Transporter Plate')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('params', models.JSONField(default=dict)),
                ('state', models.CharField(choices=[('INITIAL', 'Initial'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('ERROR', 'Error')], default='INITIAL', max_length=20, verbose_name='State')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Downloaded at')),
                ('zip_file', models.FileField(blank=True, max_length=512, storage=roadcontrol.storage_backends.PrivateMediaStorage(), upload_to=roadcontrol.models.bundle_path, verbose_name='Zip File')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Pdfs Bundle',
                'verbose_name_plural': 'Pdfs Bundles',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BsdPdf',
            fields=[
                ('company_siret', models.CharField(blank=True, max_length=20, verbose_name='Company Siret')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Company Name')),
                ('company_address', models.CharField(blank=True, max_length=512, verbose_name='Company Address')),
                ('company_contact', models.CharField(blank=True, max_length=255, verbose_name='Company Contact')),
                ('company_email', models.EmailField(blank=True, max_length=255, verbose_name='Company Email')),
                ('company_phone', models.CharField(blank=True, max_length=20, verbose_name='Company Phone')),
                ('transporter_plate', models.CharField(blank=True, max_length=20, verbose_name='Transporter Plate')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bsd_id', models.CharField(max_length=30, verbose_name='Bsd Id ')),
                ('packagings', models.CharField(blank=True, max_length=255, verbose_name='Packagings')),
                ('waste_code', models.CharField(blank=True, max_length=128, verbose_name='Waste Code')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Weight')),
                ('adr_code', models.CharField(blank=True, max_length=255, verbose_name='Adr Code')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('pdf_file', models.FileField(blank=True, max_length=512, storage=roadcontrol.storage_backends.PrivateMediaStorage(), upload_to=roadcontrol.models.bsd_path, verbose_name='Pdf')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='roadcontrol.pdfbundle', verbose_name='Bundle')),
            ],
            options={
                'verbose_name': 'Pdf Bsd',
                'verbose_name_plural': 'Pdfs Bsds',
                'ordering': ('-created_at',),
            },
        ),
    ]
