# Generated by Django 5.1.1 on 2024-09-30 16:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadcontrol', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bsdpdf',
            name='request_type',
            field=models.CharField(choices=[('ROAD_CONTROL', 'Road control'), ('BSD', 'Bsd')], default='ROAD_CONTROL', max_length=20, verbose_name='Request Type'),
        ),
        migrations.AddIndex(
            model_name='bsdpdf',
            index=models.Index(fields=['request_type'], name='roadcontrol_request_9ad607_idx'),
        ),
    ]
