# Generated by Django 5.1.5 on 2025-01-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadcontrol', '0002_bsdpdf_request_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsdpdf',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Weight'),
        ),
    ]
