# Generated by Django 4.1.7 on 2023-02-23 16:57

import uuid

import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models

import sheets.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ComputedInspectionData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "org_id",
                    models.CharField(max_length=20, verbose_name="Organization ID"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created"
                    ),
                ),
                (
                    "bsdd_created_rectified_graph",
                    models.BinaryField(blank=True, editable=True, null=True),
                ),
                (
                    "bsdd_stock_graph",
                    models.BinaryField(blank=True, editable=True, null=True),
                ),
                (
                    "bsdd_stats_graph",
                    models.BinaryField(blank=True, editable=True, null=True),
                ),
                (
                    "company_address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Company address"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Company Name"
                    ),
                ),
                (
                    "company_profiles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            max_length=255, verbose_name="Company profiles"
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("bsdd_created_rectified_data", models.JSONField(default=dict)),
                (
                    "bsdd_stats_data",
                    models.JSONField(
                        default=dict, encoder=sheets.models.CustomJSONEncoder
                    ),
                ),
                ("bsdd_stock_data", models.JSONField(default=dict)),
                ("bsda_created_rectified_data", models.JSONField(default=dict)),
                (
                    "bsda_stats_data",
                    models.JSONField(
                        default=dict, encoder=sheets.models.CustomJSONEncoder
                    ),
                ),
                ("bsda_stock_data", models.JSONField(default=dict)),
                ("bsdasri_created_rectified_data", models.JSONField(default=dict)),
                (
                    "bsdasri_stats_data",
                    models.JSONField(
                        default=dict, encoder=sheets.models.CustomJSONEncoder
                    ),
                ),
                ("bsdasri_stock_data", models.JSONField(default=dict)),
                ("input_output_waste_data", models.JSONField(default=dict)),
                ("bsff_created_rectified_data", models.JSONField(default=dict)),
                (
                    "bsff_stats_data",
                    models.JSONField(
                        default=dict, encoder=sheets.models.CustomJSONEncoder
                    ),
                ),
                ("bsff_stock_data", models.JSONField(default=dict)),
                ("bsvhu_created_rectified_data", models.JSONField(default=dict)),
                (
                    "bsvhu_stats_data",
                    models.JSONField(
                        default=dict, encoder=sheets.models.CustomJSONEncoder
                    ),
                ),
                ("bsvhu_stock_data", models.JSONField(default=dict)),
                ("storage_data", models.JSONField(default=dict)),
                ("waste_origin_data", models.JSONField(default=dict)),
                ("waste_origin_map", models.JSONField(default=dict)),
                ("outliers_data", models.JSONField(default=dict)),
                ("agreement_data", models.JSONField(default=dict)),
                ("icpe_data", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "ComputedInspectionData",
                "verbose_name_plural": "ComputedInspectionDatas",
                "ordering": ("-created",),
            },
        ),
    ]
