# Generated by Django 4.1.7 on 2023-02-27 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sheets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="computedinspectiondata",
            name="bsdd_created_rectified_graph",
        ),
        migrations.RemoveField(
            model_name="computedinspectiondata",
            name="bsdd_stats_graph",
        ),
        migrations.RemoveField(
            model_name="computedinspectiondata",
            name="bsdd_stock_graph",
        ),
    ]
