# Generated by Django 4.1.7 on 2023-02-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sheets",
            "0002_remove_computedinspectiondata_bsdd_created_rectified_graph_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="computedinspectiondata",
            name="bsda_created_rectified_graph",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="computedinspectiondata",
            name="bsda_stock_graph",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="computedinspectiondata",
            name="bsdasri_created_rectified_graph",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="computedinspectiondata",
            name="bsdasri_stock_graph",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="computedinspectiondata",
            name="bsdd_created_rectified_graph",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="computedinspectiondata",
            name="bsdd_stock_graph",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="computedinspectiondata",
            name="bsff_created_rectified_graph",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="computedinspectiondata",
            name="bsff_stock_graph",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="computedinspectiondata",
            name="bsvhu_created_rectified_graph",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="computedinspectiondata",
            name="bsvhu_stock_graph",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="computedinspectiondata",
            name="waste_origin_graph",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="computedinspectiondata",
            name="waste_origin_map_graph",
            field=models.TextField(blank=True),
        ),
    ]
