# Generated by Django 4.1.7 on 2023-02-28 20:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sheets", "0006_computedinspectiondata_pdf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="computedinspectiondata",
            name="pdf",
        ),
    ]
