# Generated by Django 4.1.7 on 2023-02-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheets", "0007_remove_computedinspectiondata_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="computedinspectiondata",
            name="pdf",
            field=models.TextField(blank=True),
        ),
    ]
