# Generated by Django 4.1.7 on 2023-03-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheets", "0008_computedinspectiondata_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="computedinspectiondata",
            name="traceability_interruptions_data",
            field=models.JSONField(default=dict),
        ),
    ]
