# Generated by Django 4.1.7 on 2023-03-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheets", "0010_computedinspectiondata_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computedinspectiondata",
            name="state",
            field=models.CharField(
                choices=[
                    ("INITIAL", "Initial"),
                    ("COMPUTED", "Computed"),
                    ("GRAPH_RENDERED", "Graph rendered"),
                    ("COMPUTED_FAILED", "Computation failed"),
                ],
                default="INITIAL",
                max_length=20,
                verbose_name="State",
            ),
        ),
    ]
