# Generated by Django 4.1.7 on 2023-04-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheets", "0011_alter_computedinspectiondata_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="computedinspectiondata",
            name="waste_is_dangerous_statements_data",
            field=models.JSONField(default=dict),
        ),
    ]
