# Generated by Django 4.2 on 2023-04-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheets", "0012_computedinspectiondata_waste_is_dangerous_statements_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="computedinspectiondata",
            name="all_bsd_data_empty",
            field=models.BooleanField(default=True),
        ),
    ]
