# Generated by Django 4.2 on 2023-05-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheets", "0014_computedinspectiondata_bsd_canceled_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="computedinspectiondata",
            name="same_emitter_recipient_data",
            field=models.JSONField(default=dict),
        ),
    ]
