# Generated by Django 4.2 on 2023-05-16 16:44

from django.db import migrations, models

import sheets.models


class Migration(migrations.Migration):
    dependencies = [
        ("sheets", "0015_computedinspectiondata_same_emitter_recipient_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="computedinspectiondata",
            name="bsdd_non_dangerous_created_rectified_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="computedinspectiondata",
            name="bsdd_non_dangerous_stats_data",
            field=models.JSONField(
                default=dict, encoder=sheets.models.CustomJSONEncoder
            ),
        ),
        migrations.AddField(
            model_name="computedinspectiondata",
            name="bsdd_non_dangerous_stock_data",
            field=models.JSONField(default=dict),
        ),
    ]
