# Generated by Django 4.2 on 2023-05-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sheets",
            "0016_computedinspectiondata_bsdd_non_dangerous_created_rectified_data_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="computedinspectiondata",
            name="bsdd_non_dangerous_created_rectified_graph",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="computedinspectiondata",
            name="bsdd_non_dangerous_stock_graph",
            field=models.TextField(blank=True),
        ),
    ]
