# Generated by Django 4.2 on 2023-05-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sheets",
            "0017_computedinspectiondata_bsdd_non_dangerous_created_rectified_graph_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="computedinspectiondata",
            name="private_individuals_collections_data",
            field=models.JSONField(default=dict),
        ),
    ]
