# Generated by Django 4.2 on 2023-05-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheets", "0018_computedinspectiondata_private_individuals_collections_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="computedinspectiondata",
            name="quantity_outliers_data",
            field=models.JSONField(default=dict),
        ),
    ]
