# Generated by Django 4.2.2 on 2023-07-26 13:55

import datetime

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheets", "0019_computedinspectiondata_quantity_outliers_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="computedinspectiondata",
            name="data_end_date",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Data End Date"),
        ),
        migrations.AddField(
            model_name="computedinspectiondata",
            name="data_start_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 7, 26, 13, 55, 7, 2085, tzinfo=datetime.timezone.utc),
                verbose_name="Data Start Date",
            ),
        ),
    ]
