# Generated by Django 4.2.2 on 2023-08-09 16:25

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheets", "0020_computedinspectiondata_data_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="computedinspectiondata",
            name="icpe_2770_graph_data",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="computedinspectiondata",
            name="data_start_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 8, 9, 16, 25, 5, 882630, tzinfo=datetime.timezone.utc),
                verbose_name="Data Start Date",
            ),
        ),
    ]
