# Generated by Django 4.2.2 on 2023-08-10 15:33

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheets", "0022_computedinspectiondata_icpe_2760_graph_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computedinspectiondata",
            name="data_start_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 1, 1, 0, 0),
                verbose_name="Data Start Date",
            ),
        ),
    ]
