# Generated by Django 4.2.2 on 2023-08-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheets", "0023_alter_computedinspectiondata_data_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="computedinspectiondata",
            name="icpe_2790_graph_data",
            field=models.TextField(blank=True),
        ),
    ]
