# Generated by Django 4.2.2 on 2023-09-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheets", "0027_computedinspectiondata_icpe_2760_data_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="computedinspectiondata",
            name="icpe_2760_graph",
        ),
        migrations.RemoveField(
            model_name="computedinspectiondata",
            name="icpe_2770_graph",
        ),
        migrations.RemoveField(
            model_name="computedinspectiondata",
            name="icpe_2790_graph",
        ),
        migrations.AddField(
            model_name="computedinspectiondata",
            name="bs_processed_without_icpe_authorization",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="computedinspectiondata",
            name="icpe_2760_data",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="computedinspectiondata",
            name="icpe_2770_data",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="computedinspectiondata",
            name="icpe_2790_data",
            field=models.TextField(blank=True),
        ),
    ]
