# Generated by Django 4.2.2 on 2023-09-08 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sheets", "0027_computedinspectiondata_icpe_2760_data_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="computedinspectiondata",
            old_name="waste_processing_without_icpe_data",
            new_name="bs_processed_without_icpe_authorization",
        ),
        migrations.RemoveField(
            model_name="computedinspectiondata",
            name="icpe_2760_data",
        ),
        migrations.RemoveField(
            model_name="computedinspectiondata",
            name="icpe_2770_data",
        ),
        migrations.RemoveField(
            model_name="computedinspectiondata",
            name="icpe_2790_data",
        ),
    ]
