# Generated by Django 4.2.2 on 2023-09-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheets", "0028_remove_computedinspectiondata_icpe_2760_graph_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="computedinspectiondata",
            name="linked_companies_data",
            field=models.JSONField(default=dict),
        ),
    ]
