# Generated by Django 4.2.2 on 2023-09-08 13:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "sheets",
            "0028_rename_waste_processing_without_icpe_data_computedinspectiondata_bs_processed_without_icpe_authoriza",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="computedinspectiondata",
            old_name="icpe_2760_graph",
            new_name="icpe_2760_data",
        ),
        migrations.RenameField(
            model_name="computedinspectiondata",
            old_name="icpe_2770_graph",
            new_name="icpe_2770_data",
        ),
        migrations.RenameField(
            model_name="computedinspectiondata",
            old_name="icpe_2790_graph",
            new_name="icpe_2790_data",
        ),
    ]
