# Generated by Django 4.2.6 on 2023-11-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheets", "0030_computedinspectiondata_company_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="computedinspectiondata",
            name="icpe_2760_graph",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="computedinspectiondata",
            name="icpe_2770_graph",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="computedinspectiondata",
            name="icpe_2790_graph",
            field=models.TextField(blank=True),
        ),
    ]
