# Generated by Django 4.2.6 on 2023-11-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheets", "0032_computedinspectiondata_bsda_worker_stats_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="computedinspectiondata",
            name="bsda_worker_quantity_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="computedinspectiondata",
            name="bsda_worker_quantity_graph",
            field=models.TextField(blank=True),
        ),
    ]
