# Generated by Django 4.2.6 on 2023-12-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheets", "0033_computedinspectiondata_bsda_worker_quantity_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="computedinspectiondata",
            name="transporter_bordereaux_stats_data",
            field=models.JSONField(default=dict),
        ),
    ]
