# Generated by Django 4.2.6 on 2023-12-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheets", "0034_computedinspectiondata_transporter_bordereaux_stats_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="computedinspectiondata",
            name="quantities_transported_stats_data",
            field=models.JSONField(default=dict),
        ),
    ]
