# Generated by Django 4.2.6 on 2023-12-04 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sheets", "0035_computedinspectiondata_quantities_transported_stats_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="computedinspectiondata",
            old_name="input_output_waste_data",
            new_name="waste_flows_data",
        ),
    ]
