# Generated by Django 4.2.6 on 2023-12-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheets", "0036_rename_input_output_waste_data_computedinspectiondata_waste_flows_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="computedinspectiondata",
            name="quantities_transported_stats_graph",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="computedinspectiondata",
            name="transporter_bordereaux_stats_graph",
            field=models.TextField(blank=True),
        ),
    ]
