# Generated by Django 4.2.6 on 2023-12-05 08:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sheets", "0037_computedinspectiondata_quantities_transported_stats_graph_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="computedinspectiondata",
            old_name="quantities_transported_stats_data",
            new_name="quantities_transported_stats_graph_data",
        ),
        migrations.RenameField(
            model_name="computedinspectiondata",
            old_name="transporter_bordereaux_stats_data",
            new_name="transporter_bordereaux_stats_graph_data",
        ),
    ]
