# Generated by Django 4.2.6 on 2023-12-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sheets",
            "0038_rename_quantities_transported_stats_data_computedinspectiondata_quantities_transported_stats_graph_d",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="computedinspectiondata",
            name="transporter_bordereaux_stats_data",
            field=models.JSONField(default=dict),
        ),
    ]
