# Generated by Django 4.2.6 on 2024-01-16 14:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sheets", "0039_computedinspectiondata_transporter_bordereaux_stats_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="computedinspectiondata",
            name="outliers_data",
        ),
    ]
