# Generated by Django 4.2.6 on 2023-12-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheets", "0039_computedinspectiondata_transporter_bordereaux_stats_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="computedinspectiondata",
            name="followed_with_pnttd_data",
            field=models.JSONField(default=dict),
        ),
    ]
