# Generated by Django 5.0.1 on 2024-01-18 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sheets", "0040_computedinspectiondata_followed_with_pnttd_data"),
        ("sheets", "0040_remove_computedinspectiondata_outliers_data"),
    ]

    operations = []
