# Generated by Django 5.0.1 on 2024-01-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sheets", "0041_merge_20240118_1755"),
    ]

    operations = [
        migrations.AddField(
            model_name="computedinspectiondata",
            name="gistrid_stats_data",
            field=models.JSONField(default=dict),
        ),
    ]
