# Generated by Django 5.0.6 on 2024-06-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0046_rename_icpe_2760_data_computedinspectiondata_icpe_2760_1_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computedinspectiondata',
            name='creation_mode',
            field=models.CharField(choices=[('WEB', 'Web'), ('API', 'Api')], default='WEB', max_length=20, verbose_name='Creation Mode'),
        ),
    ]
