# Generated by Django 5.0.6 on 2024-06-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0047_computedinspectiondata_creation_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='computedinspectiondata',
            name='pdf_rendering_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pdf rendering  start'),
        ),
        migrations.AddField(
            model_name='computedinspectiondata',
            name='pdf_rendering_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pdf rendering start'),
        ),
        migrations.AddField(
            model_name='computedinspectiondata',
            name='processing_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Processing end'),
        ),
        migrations.AddField(
            model_name='computedinspectiondata',
            name='processing_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Processing start'),
        ),
    ]
