# Generated by Django 5.0.6 on 2024-07-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0052_computedinspectiondata_eco_organisme_bordereaux_stats_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='computedinspectiondata',
            name='incinerator_outgoing_waste_data',
            field=models.JSONField(default=dict),
        ),
    ]
