# Generated by Django 5.0.6 on 2024-07-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0053_computedinspectiondata_incinerator_outgoing_waste_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='computedinspectiondata',
            name='excavated_land_quantities_graph',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='computedinspectiondata',
            name='excavated_land_quantities_graph_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='computedinspectiondata',
            name='excavated_land_statements_graph',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='computedinspectiondata',
            name='excavated_land_statements_graph_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='computedinspectiondata',
            name='excavated_land_stats_data',
            field=models.JSONField(default=dict),
        ),
    ]
