# Generated by Django 5.0.6 on 2024-07-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0054_computedinspectiondata_excavated_land_quantities_graph_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computedinspectiondata',
            name='all_rndts_data_empty',
            field=models.BooleanField(default=True),
        ),
    ]
