# Generated by Django 5.0.6 on 2024-07-30 14:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0055_computedinspectiondata_all_rndts_data_empty'),
    ]

    operations = [
        migrations.AddField(
            model_name='computedinspectiondata',
            name='company_collector_profiles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Company collector profiles'), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='computedinspectiondata',
            name='company_waste_processor_profiles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Company waste processor profiles'), blank=True, default=list, size=None),
        ),
    ]
