# Generated by Django 5.0.6 on 2024-08-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0057_computedinspectiondata_ssd_quantities_graph_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computedinspectiondata',
            name='ssd_table_data',
            field=models.JSONField(default=dict),
        ),
    ]
