# Generated by Django 5.0.7 on 2024-08-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0059_computedinspectiondata_rndts_transporter_quantities_graph_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computedinspectiondata',
            name='rndts_transporter_stats_data',
            field=models.JSONField(default=dict),
        ),
    ]
