# Generated by Django 5.1 on 2024-08-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0060_computedinspectiondata_rndts_transporter_stats_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computedinspectiondata',
            name='pdf_rendering_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pdf rendering end'),
        ),
    ]
