# Generated by Django 5.1.5 on 2025-02-06 09:18

from django.db import migrations

database_operations = [
    migrations.AlterModelTable('RegistryDownload', 'registry_registrydownload')
]

state_operations = [
    migrations.DeleteModel('RegistryDownload')
]

class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0061_alter_computedinspectiondata_pdf_rendering_end'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
