# Generated by Django 5.1.5 on 2025-02-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0062_auto_20250206_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='computedinspectiondata',
            name='voided',
            field=models.BooleanField(blank=True, default=False, verbose_name='Data voided'),
        ),
    ]
