# Generated by Django 5.2 on 2025-04-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0063_computedinspectiondata_voided'),
    ]

    operations = [
        migrations.AddField(
            model_name='computedinspectiondata',
            name='data_extraction_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data extraction end'),
        ),
        migrations.AddField(
            model_name='computedinspectiondata',
            name='data_extraction_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data extraction start'),
        ),
    ]
