# Generated by Django 5.2 on 2025-05-12 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0064_computedinspectiondata_data_extraction_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computedinspectiondata',
            old_name='all_rndts_data_empty',
            new_name='all_registry_data_empty',
        ),
        migrations.RenameField(
            model_name='computedinspectiondata',
            old_name='rndts_transporter_quantities_graph',
            new_name='registry_transporter_quantities_graph',
        ),
        migrations.RenameField(
            model_name='computedinspectiondata',
            old_name='rndts_transporter_quantities_graph_data',
            new_name='registry_transporter_quantities_graph_data',
        ),
        migrations.RenameField(
            model_name='computedinspectiondata',
            old_name='rndts_transporter_statement_stats_graph',
            new_name='registry_transporter_statement_stats_graph',
        ),
        migrations.RenameField(
            model_name='computedinspectiondata',
            old_name='rndts_transporter_statement_stats_graph_data',
            new_name='registry_transporter_statement_stats_graph_data',
        ),
        migrations.RenameField(
            model_name='computedinspectiondata',
            old_name='rndts_transporter_stats_data',
            new_name='registry_transporter_stats_data',
        ),
    ]
