# Generated by Django 5.2.1 on 2025-06-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0065_rename_all_rndts_data_empty_computedinspectiondata_all_registry_data_empty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computedinspectiondata',
            name='company_has_enabled_registry_dnd_from_bsd_since',
            field=models.DateTimeField(default=None, null=True, verbose_name='Company has enabled registry dnd from bsd since'),
        ),
    ]
