# Generated by Django 5.1.5 on 2025-02-06 16:27

import datetime

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sheets', '0062_auto_20250206_1018'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='RegistryDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(max_length=20, verbose_name='Organization ID')),
                ('data_start_date', models.DateTimeField(default=datetime.datetime(2022, 1, 1, 0, 0), verbose_name='Data Start Date')),
                ('data_end_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data End Date')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('created_by', models.EmailField(blank=True, max_length=254, verbose_name='Created by x')),
            ],
            options={
                'verbose_name': 'Téléchargement de registre',
                'verbose_name_plural': 'Téléchargements de registre',
                'ordering': ('-created',),
            },
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
