# Generated by Django 5.0.3 on 2024-04-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='monaiot_connexion',
            field=models.BooleanField(default=False, help_text='Did this user already log in with monaiot ?', verbose_name='Mon aiot connexion'),
        ),
        migrations.AddField(
            model_name='user',
            name='monaiot_signup',
            field=models.BooleanField(default=False, help_text='Did this user sign up in with monaiot ?', verbose_name='Mon aiot inscription'),
        ),
    ]
