# Generated by Django 5.0.6 on 2024-06-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_monaiot_connexion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('HUMAN', 'Human'), ('API', 'api')], default='HUMAN', max_length=30, verbose_name='User Type'),
        ),
    ]
