# Generated by Django 5.1.2 on 2024-10-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_category',
            field=models.CharField(choices=[('STAFF_TD', 'Staff Trackdéchets'), ('ADMINISTRATION_CENTRALE', 'Administration centrale'), ('INSPECTEUR_ICPE', 'Inspecteur ICPE'), ('CTT', 'CTT - contrôleur des transports routiers'), ('INSPECTION_TRAVAIL', 'Inspection du travail'), ('GENDARMERIE', 'Gendarmerie'), ('ARS', 'ARS')], default='INSPECTEUR_ICPE', max_length=30, verbose_name='User Category'),
        ),
    ]
