# Generated by Django 5.1.5 on 2025-02-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_user_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_category',
            field=models.CharField(choices=[('STAFF_TD', 'Staff Trackdéchets'), ('ADMINISTRATION_CENTRALE', 'Administration centrale'), ('INSPECTEUR_ICPE', 'Inspecteur ICPE'), ('CTT', 'CTT - Contrôleur des transports routiers'), ('INSPECTION_TRAVAIL', 'Inspection du travail'), ('GENDARMERIE', 'Gendarmerie'), ('ARS', 'ARS'), ('DOUANE', 'Douane'), ('OBSERVATOIRE', 'Observatoire')], default='INSPECTEUR_ICPE', max_length=30, verbose_name='User Category'),
        ),
    ]
