# Generated by Django 5.1.6 on 2025-02-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_user_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oidc_connexion',
            field=models.CharField(blank=True, choices=[('MONAIOT', 'MonAIOT'), ('PROCONNECT', 'Proconnect')], help_text='Did this user already log in with OIDC ?', verbose_name='OIDC connexion'),
        ),
        migrations.AddField(
            model_name='user',
            name='oidc_signup',
            field=models.CharField(blank=True, choices=[('MONAIOT', 'MonAIOT'), ('PROCONNECT', 'Proconnect')], help_text='Did this user sign up in with OIDC ?', verbose_name='OIDC inscription'),
        ),
    ]
