# Generated by Django 5.1.6 on 2025-03-03 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20250227_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='monaiot_connexion',
        ),
        migrations.RemoveField(
            model_name='user',
            name='monaiot_signup',
        ),
    ]
