# Generated by Django 5.1.6 on 2025-02-20 14:02

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OidcLogin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('MONAIOT', 'MonAIOT')], max_length=30, verbose_name='Provider')),
                ('info', models.JSONField(default=dict, verbose_name='Info')),
                ('account_created', models.BooleanField(default=False, verbose_name='Account Created')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Login OIDC',
                'verbose_name_plural': 'Logins OIDC',
                'ordering': ('-created_at',),
            },
        ),
    ]
