# Generated by Django 5.1.6 on 2025-02-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oidclogin',
            name='provider',
            field=models.CharField(choices=[('MONAIOT', 'MonAIOT'), ('PROCONNECT', 'Proconnect')], max_length=30, verbose_name='Provider'),
        ),
    ]
