INSERT INTO "raw_zone_trackdechets"."company"("_sdc_batched_at", "_sdc_deleted_at", "_sdc_extracted_at", "address",
                                              "allowbsdasritakeoverwithoutsignature", "brokerreceiptid",
                                              "codedepartement", "codenaf", "companytypes", "contact", "contactemail",
                                              "contactphone", "createdat", "ecoorganismeagreements", "gerepid",
                                              "givenname", "id", "latitude", "longitude", "name", "securitycode",
                                              "siret", "traderreceiptid", "transporterreceiptid", "updatedat",
                                              "vatnumber", "verificationcode", "verificationcomment",
                                              "verificationmode", "verificationstatus", "verifiedat",
                                              "vhuagrementbroyeurid", "vhuagrementdemolisseurid", "website",
                                              "workercertificationid", "orgid")
VALUES (E'2022-09-22 16:17:05.91245', NULL, E'2022-09-22 16:17:05.164535', E'6 PL JACQUES FROMENT 75018 PARIS 18',
        FALSE, NULL, E'75', E'6201Z', E'["TRANSPORTER"]', NULL, NULL, NULL, E'2018-12-10 19:21:09.819', E'[]', NULL,
        NULL, E'abcdef123', 48.891059, 2.331283, E'LACOMPANY', 8699, E'12345678912345', NULL, NULL,
        E'2022-09-19 22:13:07.206688', NULL, E'44319', NULL, E'MANUAL', E'VERIFIED', E'2021-04-28 14:50:58.262', NULL,
        NULL, NULL, NULL, NULL);

INSERT INTO "raw_zone_trackdechets"."form"("_sdc_batched_at", "_sdc_deleted_at", "_sdc_extracted_at",
                                           "brokercompanyaddress", "brokercompanycontact", "brokercompanymail",
                                           "brokercompanyname", "brokercompanyphone", "brokercompanysiret",
                                           "brokerdepartment", "brokerreceipt", "brokervaliditylimit", "createdat",
                                           "currenttransportersiret", "customid", "ecoorganismename",
                                           "ecoorganismesiret", "emittedat", "emittedby", "emittedbyecoorganisme",
                                           "emittercompanyaddress", "emittercompanycontact", "emittercompanymail",
                                           "emittercompanyname", "emittercompanyominumber", "emittercompanyphone",
                                           "emittercompanysiret", "emitterisforeignship", "emitterisprivateindividual",
                                           "emitterpickupsite", "emittertype", "emitterworksiteaddress",
                                           "emitterworksitecity", "emitterworksiteinfos", "emitterworksitename",
                                           "emitterworksitepostalcode", "forwardedinid", "id", "isaccepted",
                                           "isdeleted", "isimportedfrompaper", "nextdestinationcompanyaddress",
                                           "nextdestinationcompanycontact", "nextdestinationcompanycountry",
                                           "nextdestinationcompanymail", "nextdestinationcompanyname",
                                           "nextdestinationcompanyphone", "nextdestinationcompanysiret",
                                           "nextdestinationprocessingoperation", "nexttransportersiret",
                                           "notraceability", "ownerid", "processedat", "processedby",
                                           "processingoperationdescription", "processingoperationdone",
                                           "quantitygrouped", "quantityreceived", "quantityreceivedtype", "readableid",
                                           "receivedat", "receivedby", "recipientcap", "recipientcompanyaddress",
                                           "recipientcompanycontact", "recipientcompanymail", "recipientcompanyname",
                                           "recipientcompanyphone", "recipientcompanysiret", "recipientistempstorage",
                                           "recipientprocessingoperation", "sentat", "sentby", "signedat", "signedby",
                                           "signedbytransporter", "status", "takenoverat", "takenoverby",
                                           "tradercompanyaddress", "tradercompanycontact", "tradercompanymail",
                                           "tradercompanyname", "tradercompanyphone", "tradercompanysiret",
                                           "traderdepartment", "traderreceipt", "tradervaliditylimit",
                                           "transportercompanyaddress", "transportercompanycontact",
                                           "transportercompanymail", "transportercompanyname",
                                           "transportercompanyphone", "transportercompanysiret",
                                           "transportercompanyvatnumber", "transportercustominfo",
                                           "transporterdepartment", "transporterisexemptedofreceipt",
                                           "transporternumberplate", "transporterreceipt", "transportertransportmode",
                                           "transportervaliditylimit", "updatedat", "wasteacceptationstatus",
                                           "wastedetailsanalysisreferences", "wastedetailscode",
                                           "wastedetailsconsistence", "wastedetailsisdangerous",
                                           "wastedetailslandidentifiers", "wastedetailsname", "wastedetailsonucode",
                                           "wastedetailspackaginginfos", "wastedetailsparcelnumbers", "wastedetailspop",
                                           "wastedetailsquantity", "wastedetailsquantitytype", "wasterefusalreason",
                                           "nextdestinationcompanyvatnumber", "intermediariessirets",
                                           "recipientssirets", "transporterssirets",
                                           "nextdestinationnotificationnumber")
VALUES (E'2022-09-22 16:18:36.652848', NULL, E'2022-09-22 16:18:14.726197', NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, E'2023-05-17 00:00:00', NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        E'199 RUE JEAN JAURES, 79000 NIORT', E'LOGEAY Hugo', E'hugo.logeay@geneve-occasion.fr', E'GENEVE OCCASION',
        NULL, E'0689801706', E'12345678912345', FALSE, FALSE, NULL, E'PRODUCER', NULL, NULL, NULL, NULL, NULL, NULL,
        E'cjri1edxj0gok0703ib7go6bs', NULL, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        E'cjri0yml20ghr0703qg5df47y', NULL, NULL, NULL, NULL, 0, NULL, E'REAL', E'TD-19-AAA00058', NULL, NULL, NULL,
        E'34 RUE DES AUBERGES, 85260 MONTREVERD', E'KERDRAON Ronan', E'administratif@metalrecycling.fr',
        E'SARL METAL RECYCLING', E'0625308940', E'80852997800021', FALSE, E'R 8', NULL, NULL, NULL, NULL, NULL,
        E'SEALED', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        E'34 RUE DES AUBERGES, 85260 MONTREVERD', E'kerdraon Ronan', E'administratif@metalrecycling.fr',
        E'SARL METAL RECYCLING', E'0625308940', E'80852997800021', NULL, NULL, E'85', NULL, NULL, E'2018-20', E'ROAD',
        E'2023-09-18 00:00:00', E'2021-12-20 10:59:29.093', NULL, E'[]', E'16 08 07*', NULL, TRUE, E'[]', E'catalyseur',
        NULL, E'[{"type": "AUTRE", "other": "unité", "quantity": 266}]', E'[]', FALSE, 0.931, E'ESTIMATED', NULL, NULL,
        NULL, NULL, NULL, NULL);
INSERT INTO "raw_zone_trackdechets"."bsda"("_sdc_batched_at", "_sdc_deleted_at", "_sdc_extracted_at",
                                           "brokercompanyaddress", "brokercompanycontact", "brokercompanymail",
                                           "brokercompanyname", "brokercompanyphone", "brokercompanysiret",
                                           "brokerrecepissedepartment", "brokerrecepissenumber",
                                           "brokerrecepissevaliditylimit", "createdat", "destinationcap",
                                           "destinationcompanyaddress", "destinationcompanycontact",
                                           "destinationcompanymail", "destinationcompanyname",
                                           "destinationcompanyphone", "destinationcompanysiret",
                                           "destinationcustominfo", "destinationoperationcode",
                                           "destinationoperationdate", "destinationoperationdescription",
                                           "destinationoperationnextdestinationcap",
                                           "destinationoperationnextdestinationcompanyaddress",
                                           "destinationoperationnextdestinationcompanycontact",
                                           "destinationoperationnextdestinationcompanymail",
                                           "destinationoperationnextdestinationcompanyname",
                                           "destinationoperationnextdestinationcompanyphone",
                                           "destinationoperationnextdestinationcompanysiret",
                                           "destinationoperationnextdestinationcompanyvatnumber",
                                           "destinationoperationnextdestinationplannedoperationcode",
                                           "destinationoperationsignatureauthor", "destinationoperationsignaturedate",
                                           "destinationplannedoperationcode", "destinationreceptionacceptationstatus",
                                           "destinationreceptiondate", "destinationreceptionrefusalreason",
                                           "destinationreceptionweight", "ecoorganismename", "ecoorganismesiret",
                                           "emittercompanyaddress", "emittercompanycontact", "emittercompanymail",
                                           "emittercompanyname", "emittercompanyphone", "emittercompanysiret",
                                           "emittercustominfo", "emitteremissionsignatureauthor",
                                           "emitteremissionsignaturedate", "emitterisprivateindividual",
                                           "emitterpickupsiteaddress", "emitterpickupsitecity",
                                           "emitterpickupsiteinfos", "emitterpickupsitename",
                                           "emitterpickupsitepostalcode", "forwardingid", "groupedinid", "id",
                                           "isdeleted", "isdraft", "packagings", "repackagedinid", "status",
                                           "transportercompanyaddress", "transportercompanycontact",
                                           "transportercompanymail", "transportercompanyname",
                                           "transportercompanyphone", "transportercompanysiret",
                                           "transportercompanyvatnumber", "transportercustominfo",
                                           "transporterrecepissedepartment", "transporterrecepisseisexempted",
                                           "transporterrecepissenumber", "transporterrecepissevaliditylimit",
                                           "transportertransportmode", "transportertransportplates",
                                           "transportertransportsignatureauthor", "transportertransportsignaturedate",
                                           "transportertransporttakenoverat", "type", "updatedat", "wasteadr",
                                           "wastecode", "wasteconsistence", "wastefamilycode", "wastematerialname",
                                           "wastepop", "wastesealnumbers", "weightisestimate", "weightvalue",
                                           "workercompanyaddress", "workercompanycontact", "workercompanymail",
                                           "workercompanyname", "workercompanyphone", "workercompanysiret",
                                           "workerisdisabled", "workerworkhasemitterpapersignature",
                                           "workerworksignatureauthor", "workerworksignaturedate",
                                           "workercertificationcertificationnumber",
                                           "workercertificationhassubsectionfour",
                                           "workercertificationhassubsectionthree", "workercertificationorganisation",
                                           "workercertificationvaliditylimit", "intermediariesorgids")
VALUES (E'2022-09-22 16:14:35.207331', NULL, E'2022-09-22 16:14:33.890123', E'53 ALL DE LA FORGE 35220 CHATEAUBOURG',
        E'BOUETARD Ronan', E'r.bouetard@portiq.fr', E'SKYNSEMI', E'0640111078', E'84239102100016', E'35', E'2021-44',
        E'2026-05-26 00:00:00', E'2021-09-20 12:02:04.272', NULL, E'53 Allée de la Forge 35220 Châteaubourg', NULL,
        NULL, E'SKYNSEMI', NULL, E'84239102100016', NULL, NULL, NULL, NULL, NULL,
        E'RTE DE SCEAUX 49220 CHENILLE CHAMPTEUSSE', NULL, NULL,
        E'SOCIETE  D EXPLOITATION DE LA DECHARGE ANGEVINE SEDA', NULL, E'32283805300062', NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, NULL, NULL, NULL, E'2247 Route de Camaret 84100 Orange', NULL, NULL, E'ORANGE BUSINESS', NULL,
        E'52920916500016', NULL, NULL, NULL, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        E'BSDA-20210920-EN3PSKB72', TRUE, TRUE, E'[{"type": "BIG_BAG", "other": "", "quantity": 5}]', NULL, E'INITIAL',
        E'Impasse de la Vallée Verte 53940 Le Genest-Saint-Isle', E'TESSIER Jérémy', NULL,
        E'TRANSPORTS GRUE HAUTBOIS TESSIER', NULL, E'52419684700023', NULL, NULL, NULL, NULL, NULL, NULL, E'ROAD',
        E'[]', NULL, NULL, NULL, E'OTHER_COLLECTIONS', E'2021-10-25 19:09:31.932', NULL, E'17 06 05*', E'SOLIDE', E'6',
        E'Débris de chantier', FALSE, E'["14545", "16526", "21215", "32165"]', FALSE, 1500,
        E'6 Rue de la Giraudière 35530 Noyal-sur-Vilaine', E'Angélique Prenveille', E'secretariat@soveamiante.fr',
        E'SOVEAMIANT', E'0299041885', E'80304415500023', NULL, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);


INSERT INTO "raw_zone_trackdechets"."bsdasri"("_sdc_batched_at", "_sdc_deleted_at", "_sdc_extracted_at", "createdat",
                                              "destinationcompanyaddress", "destinationcompanycontact",
                                              "destinationcompanymail", "destinationcompanyname",
                                              "destinationcompanyphone", "destinationcompanysiret",
                                              "destinationcustominfo", "destinationoperationcode",
                                              "destinationoperationdate", "destinationoperationsignatureauthor",
                                              "destinationoperationsignaturedate",
                                              "destinationreceptionacceptationstatus", "destinationreceptiondate",
                                              "destinationreceptionsignatureauthor",
                                              "destinationreceptionsignaturedate",
                                              "destinationreceptionwasterefusalreason",
                                              "destinationreceptionwasterefusedweightvalue",
                                              "destinationreceptionwastevolume", "destinationreceptionwasteweightvalue",
                                              "destinationwastepackagings", "ecoorganismename", "ecoorganismesiret",
                                              "emissionsignatoryid", "emittedbyecoorganisme", "emittercompanyaddress",
                                              "emittercompanycontact", "emittercompanymail", "emittercompanyname",
                                              "emittercompanyphone", "emittercompanysiret", "emittercustominfo",
                                              "emitteremissionsignatureauthor", "emitteremissionsignaturedate",
                                              "emitterpickupsiteaddress", "emitterpickupsitecity",
                                              "emitterpickupsiteinfos", "emitterpickupsitename",
                                              "emitterpickupsitepostalcode", "emitterwastepackagings",
                                              "emitterwastevolume", "emitterwasteweightisestimate",
                                              "emitterwasteweightvalue", "groupedinid", "handedovertorecipientat", "id",
                                              "identificationnumbers", "isdeleted", "isdraft",
                                              "isemissiondirecttakenover", "isemissiontakenoverwithsecretcode",
                                              "operationsignatoryid", "receptionsignatoryid", "status",
                                              "synthesizedinid", "transportsignatoryid", "transporteracceptationstatus",
                                              "transportercompanyaddress", "transportercompanycontact",
                                              "transportercompanymail", "transportercompanyname",
                                              "transportercompanyphone", "transportercompanysiret",
                                              "transportercompanyvatnumber", "transportercustominfo",
                                              "transporterrecepissedepartment", "transporterrecepissenumber",
                                              "transporterrecepissevaliditylimit", "transportertakenoverat",
                                              "transportertransportmode", "transportertransportplates",
                                              "transportertransportsignatureauthor",
                                              "transportertransportsignaturedate", "transporterwastepackagings",
                                              "transporterwasterefusalreason", "transporterwasterefusedweightvalue",
                                              "transporterwastevolume", "transporterwasteweightisestimate",
                                              "transporterwasteweightvalue", "type", "updatedat", "wasteadr",
                                              "wastecode", "synthesisemittersirets", "transporterrecepisseisexempted")
VALUES (E'2022-09-22 16:15:15.750166', NULL, E'2022-09-22 16:15:13.383913', E'2021-07-07 13:00:45.881',
        E'12 Rue des Bouillots 03500 Bayet', NULL, NULL, E'LUCANE', NULL, E'12345678912345', NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, E'[]', NULL, NULL, NULL, FALSE,
        E'4 QUAI DE LA JONCTION 58000 NEVERS', E'VALLET David', E'david.vallet@g-ushin.com', E'U-SHIN FRANCE',
        E'0386603397', E'78994487300031', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        E'[{"type": "BOITE_CARTON", "other": "", "volume": 25, "quantity": 1}]', 25, TRUE, NULL, NULL, NULL,
        E'DASRI-20210707-DGT2YRN57', E'[]', TRUE, TRUE, FALSE, FALSE, NULL, NULL, E'INITIAL', NULL, NULL, NULL,
        E'6 Rue de la Prairie 58000 Challuy', E'M. Laboue', E'proxidas@email.fr', E'PROXIDAS', E'0202022020',
        E'83415582200010', NULL, NULL, NULL, NULL, NULL, NULL, E'ROAD', E'[]', NULL, NULL, E'[]', NULL, NULL, 0, NULL,
        NULL, E'SIMPLE', E'2022-04-08 09:29:57.629257', NULL, E'18 01 03*', NULL, NULL);


INSERT INTO "raw_zone_trackdechets"."bsff"("_sdc_batched_at", "_sdc_deleted_at", "_sdc_extracted_at", "createdat",
                                           "destinationcompanyaddress", "destinationcompanycontact",
                                           "destinationcompanymail", "destinationcompanyname",
                                           "destinationcompanyphone", "destinationcompanysiret",
                                           "destinationcustominfo", "destinationoperationcode",
                                           "destinationoperationnextdestinationcompanyaddress",
                                           "destinationoperationnextdestinationcompanycontact",
                                           "destinationoperationnextdestinationcompanymail",
                                           "destinationoperationnextdestinationcompanyname",
                                           "destinationoperationnextdestinationcompanyphone",
                                           "destinationoperationnextdestinationcompanysiret",
                                           "destinationoperationnextdestinationcompanyvatnumber",
                                           "destinationoperationsignatureauthor", "destinationoperationsignaturedate",
                                           "destinationplannedoperationcode", "destinationreceptionacceptationstatus",
                                           "destinationreceptiondate", "destinationreceptionrefusalreason",
                                           "destinationreceptionsignatureauthor", "destinationreceptionsignaturedate",
                                           "destinationreceptionweight", "emittercompanyaddress",
                                           "emittercompanycontact", "emittercompanymail", "emittercompanyname",
                                           "emittercompanyphone", "emittercompanysiret", "emittercustominfo",
                                           "emitteremissionsignatureauthor", "emitteremissionsignaturedate",
                                           "forwardingid", "groupedinid", "id", "isdeleted", "isdraft",
                                           "repackagedinid", "status", "transportercompanyaddress",
                                           "transportercompanycontact", "transportercompanymail",
                                           "transportercompanyname", "transportercompanyphone",
                                           "transportercompanysiret", "transportercompanyvatnumber",
                                           "transportercustominfo", "transporterrecepissedepartment",
                                           "transporterrecepissenumber", "transporterrecepissevaliditylimit",
                                           "transportertransportmode", "transportertransportplates",
                                           "transportertransportsignatureauthor", "transportertransportsignaturedate",
                                           "transportertransporttakenoverat", "type", "updatedat", "wasteadr",
                                           "wastecode", "wastedescription", "weightisestimate", "weightvalue",
                                           "destinationcap", "detenteurcompanysirets")
VALUES (E'2022-09-22 16:16:58.733383', NULL, E'2022-09-22 16:16:58.208017', E'2021-08-05 16:05:04.715',
        E'15 RUE ARTHUR RANC 86000 POITIERS', E'FLAHAUT Emmanuel', E'flahaut17540@gmail.com',
        E'DIRECTION REGIONALE DE L\'ENVIRONNEMENT DE L\'AMENAGEMENT ET DU LOGEMENT NOUVELLE-AQUITAINE', E'0615103990',
        E'12345678912345', NULL, E'R3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, E'manu', E'2022-05-18 15:19:43.389',
        E'R2', E'ACCEPTED', E'2022-05-18 15:18:41.577', NULL, E'manu', E'2022-05-18 15:18:56.276', 5,
        E'148 Route d\'Aiffres 79000 Niort', E'Emmanuel', E'flahaut17540@gmail.com', E'BOULANGERIE AU 148',
        E'0765432109', E'81232991000010', NULL, E'emetteur', E'2021-08-05 16:05:08.322', NULL, NULL,
        E'FF-1', FALSE, FALSE, NULL, E'PROCESSED', E'15 Rue Arthur Ranc 86000 Poitiers',
        E'Muriel Robin', E'claire.vigier@live.fr',
        E'DIRECTION REGIONALE DE L\'ENVIRONNEMENT DE L\'AMENAGEMENT ET DU LOGEMENT NOUVELLE-AQUITAINE', E'0998765434',
        E'13001045700013', NULL, NULL, E'79', E'Tests123', E'2030-08-30 00:00:00', E'ROAD', E'[]', E'chofeur',
        E'2021-08-05 16:05:33.318', NULL, E'TRACER_FLUIDE', E'2022-05-18 15:19:43.54861',
        E'UN 1078, Gaz frigorifique NSA (Gaz réfrigérant, NSA), 2.2 (C/E)', E'14 06 01*', E'R222', TRUE, 7, NULL, NULL);

INSERT INTO "raw_zone_trackdechets"."bsffpackaging"("_sdc_batched_at", "_sdc_deleted_at", "_sdc_extracted_at",
                                                    "acceptationdate", "acceptationrefusalreason",
                                                    "acceptationsignatureauthor", "acceptationsignaturedate",
                                                    "acceptationstatus", "acceptationwastecode",
                                                    "acceptationwastedescription", "acceptationweight", "bsffid", "id",
                                                    "nextpackagingid", "numero", "operationcode", "operationdate",
                                                    "operationdescription", "operationnextdestinationcap",
                                                    "operationnextdestinationcompanyaddress",
                                                    "operationnextdestinationcompanycontact",
                                                    "operationnextdestinationcompanymail",
                                                    "operationnextdestinationcompanyname",
                                                    "operationnextdestinationcompanyphone",
                                                    "operationnextdestinationcompanysiret",
                                                    "operationnextdestinationcompanyvatnumber",
                                                    "operationnextdestinationplannedoperationcode",
                                                    "operationnotraceability", "operationsignatureauthor",
                                                    "operationsignaturedate", "other", "type", "volume", "weight",
                                                    "emissionnumero")
VALUES (E'2023-05-03 00:00:24.423301', NULL, E'2023-05-03 00:00:23.945267', NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        NULL, E'FF-1', E'cl5r8cfiu00014syk7b3u8egu', NULL, E'597832', NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, E'AUTRE', 0, 0, E'597832');


INSERT INTO "raw_zone_trackdechets"."bsvhu"("_sdc_batched_at", "_sdc_deleted_at", "_sdc_extracted_at", "createdat",
                                            "destinationagrementnumber", "destinationcompanyaddress",
                                            "destinationcompanycontact", "destinationcompanymail",
                                            "destinationcompanyname", "destinationcompanyphone",
                                            "destinationcompanysiret", "destinationcustominfo",
                                            "destinationoperationcode", "destinationoperationdate",
                                            "destinationoperationnextdestinationcompanyaddress",
                                            "destinationoperationnextdestinationcompanycontact",
                                            "destinationoperationnextdestinationcompanymail",
                                            "destinationoperationnextdestinationcompanyname",
                                            "destinationoperationnextdestinationcompanyphone",
                                            "destinationoperationnextdestinationcompanysiret",
                                            "destinationoperationnextdestinationcompanyvatnumber",
                                            "destinationoperationsignatureauthor", "destinationoperationsignaturedate",
                                            "destinationplannedoperationcode", "destinationreceptionacceptationstatus",
                                            "destinationreceptiondate", "destinationreceptionidentificationnumbers",
                                            "destinationreceptionidentificationtype", "destinationreceptionquantity",
                                            "destinationreceptionrefusalreason", "destinationreceptionweight",
                                            "destinationtype", "emitteragrementnumber", "emittercompanyaddress",
                                            "emittercompanycontact", "emittercompanymail", "emittercompanyname",
                                            "emittercompanyphone", "emittercompanysiret", "emittercustominfo",
                                            "emitteremissionsignatureauthor", "emitteremissionsignaturedate", "id",
                                            "identificationnumbers", "identificationtype", "isdeleted", "isdraft",
                                            "packaging", "quantity", "status", "transportercompanyaddress",
                                            "transportercompanycontact", "transportercompanymail",
                                            "transportercompanyname", "transportercompanyphone",
                                            "transportercompanysiret", "transportercompanyvatnumber",
                                            "transportercustominfo", "transporterrecepissedepartment",
                                            "transporterrecepissenumber", "transporterrecepissevaliditylimit",
                                            "transportertransportplates", "transportertransportsignatureauthor",
                                            "transportertransportsignaturedate", "transportertransporttakenoverat",
                                            "updatedat", "wastecode", "weightisestimate", "weightvalue",
                                            "transporterrecepisseisexempted")
VALUES (E'2023-01-12 00:00:19.994463', NULL, E'2023-01-12 00:00:19.772463', E'2021-06-21 15:28:15.186', E'a',
        E'64 GRANDE RUE 70200 VY-LES-LURE', E'aa aa', E'test@test.fr', E'L.A. BOULANGERIE', E'0114789526',
        E'12345678912345', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, E'R 4', NULL, NULL,
        E'[]', NULL, NULL, NULL, NULL, E'BROYEUR', E'13245', E'6 Place Jacques Froment 75018 Paris', E'Claire VIGIER',
        E'claire@frontier.team', E'CORETECH', E'0289765432', E'84392249300013', NULL, NULL, NULL,
        E'VHU-1', E'["1", "2", "3", "54"]', E'NUMERO_ORDRE_REGISTRE_POLICE', TRUE, FALSE, E'UNITE', 4,
        E'INITIAL', E'15 Rue Arthur Ranc 86000 Poitiers', E'Muriel Robin', E'claire.vigier@live.fr',
        E'DIRECTION REGIONALE DE L\'ENVIRONNEMENT DE L\'AMENAGEMENT ET DU LOGEMENT NOUVELLE-AQUITAINE', E'0998765434',
        E'13001045700013', NULL, NULL, E'79', E'Tests123', E'2030-08-30 00:00:00', E'[]', NULL, NULL, NULL,
        E'2023-01-11 16:31:11.339', E'16 01 06', NULL, 3000, NULL);