# Generated by Django 5.2.1 on 2025-05-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(blank=True, verbose_name="Bannière d'information - titre")),
                ('banner_content', models.TextField(blank=True, verbose_name="Bannière d'information - contenu")),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
