name: TD Inspection CI

on: pull_request

env:
  DATABASE_URL:postgresql://admin:postgres@localhost/inspection_test
  WAREHOUSE_URL:postgresql://admin:postgres@localhost/tdwarehouse_test
  ADMIN_SLUG:admin

defaults:
  run:
    working-directory: src

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: inspection_test
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pipenv wheel

    - id: cache-pipenv
      uses: actions/cache@v2
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

    - name: Install python dependencies
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: |
        pipenv install --deploy --dev

    - name: Lint
      run: pipenv run flake8

    - name: Black
      run: pipenv run black --check .

    - name: Run Tests
      run: |
        pipenv run pytest
      env:
        DJANGO_SETTINGS_MODULE: core.settings.test
