name: TD Inspection CI

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: inspection_test
        ports: [ '5432:5432' ]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Set locales
        run: sudo apt-get install -y tzdata locales && sudo locale-gen fr_FR && sudo dpkg-reconfigure --frontend=noninteractive locales


      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - id: cache-pipenv
        uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install python dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev

      - name: Ruff Linting
        run: pipenv run ruff .

      - name: Ruff Formatting
        run: pipenv run ruff format --check .

      - name: Run Tests
        working-directory: src
        run: |
          pipenv run pytest
        env:
          DJANGO_SETTINGS_MODULE: core.settings.test
          DATABASE_URL: postgresql://admin:postgres@localhost/inspection_test
          WAREHOUSE_URL: postgresql://admin:postgres@localhost/tdwarehouse_test
          DEFENDER_REDIS_URL: redis://localhost:6379/0
          ADMIN_SLUG: admin
          MESSAGE_RECIPIENTS: lorem@ipsum.lol
