# Generated by Django 5.1.5 on 2025-02-05 14:48

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bsd_type', models.CharField(choices=[('BSDD', 'Déchets dangereux'), ('BSDA', 'Amiante'), ('BSDASRI', 'DASRI'), ('BSVHU', 'VHU'), ('BSFF', 'Fluides Frigo')], max_length=20, verbose_name='Bsd Type')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Export name')),
                ('s3_path', models.CharField(blank=True, max_length=512, verbose_name='S3 path')),
                ('last_modified', models.DateTimeField(blank=True, null=True, verbose_name='LAst modified')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Size')),
                ('verbose_size', models.CharField(blank=True, max_length=64, verbose_name='Verbose size')),
            ],
            options={
                'verbose_name': 'Data Export',
                'verbose_name_plural': 'Data Exports',
                'ordering': ('-created_at',),
            },
        ),
    ]
