# Generated by Django 5.1.5 on 2025-02-05 14:50

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_exports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExportDownload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bsd_type', models.CharField(max_length=20, verbose_name='Bsd Type')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user', models.CharField(max_length=256, verbose_name='User email')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Data Export Download',
                'verbose_name_plural': 'Data Exports Downloads',
                'ordering': ('-created_at',),
            },
        ),
    ]
